In [6]:
import numpy as np
# I am making a two dimensional array and sum its elements according to x and y axis.
x=([2,4,6],[5,3,1],[9,8,4])
arr=np.array(x)
# successfully created 2d array.
# I want o sum the all the axis value of wd array.
arr.sum(axis=0)

array([16, 15, 11])

Y-Axis

In [7]:
arr.sum(axis=1)

array([12,  9, 21])

Transpose

In [8]:
# Converting rows to column and column to rows.
arr.T

array([[2, 5, 9],
       [4, 3, 8],
       [6, 1, 4]])

Sum them according to X and Y axis

In [11]:
arr.T
arr.sum(axis=0)


array([16, 15, 11])

In [12]:
arr.sum(axis=1)

array([12,  9, 21])

In [16]:
arr
arr.T
# want to check the dimensions of Array
arr.ndim

2